class Users():
     def __init__(self):
         self.users = {
                "Abaev" : "XWiki.abaev",
                "Abeck" : None,
                "Adam.congdon" : None,
                "Addbug" : None,
                "Adenisov" : None,
                "Aevstratova" : "XWiki.aevstratova",
                "Agolubnichy" : None,
                "Alan Bolte" : None,
                "Aleksandr Orekhov" : None,
                "Alex Nvm" : "XWiki.azaytsev",
                "Alexander Korolev" : 'XWiki.akorolev',
                "Alexander Lupashku" : "XWiki.alupashku",
                "Alexander Yakimenko" : None,
                "Alexey Gavrunov" : "XWiki.agavrunov",
                "Alexey Zaytsev" : "XWiki.azaytsev",
                "Alexey.gladkih" : None,
                "AlexG" : "XWiki.agerasimov",
                "ALukinov" : "XWiki.alukinov",
                "Alupashku" : "XWiki.alupashku",
                "Anastasia Brukhanda" : "XWiki.abrukhanda",
                "Andrej Dudkin" : None,
                "Andreyzayn" : "XWiki.andreyzainutdinov",
                "Anton Lee" : None,
                "Artem Naskal" : "XWiki.ArtemNaskal",
                "AShelemin" : None,
                "Avenediktov" : None,
                "Ben.Milligan" : None,
                "BenCreamer" : None,
                "Bloredana" : "XWiki.lbugaciu",
                "Cgray" : None,
                "Cgriffith" : None,
                "Cody.ault" : None,
                "DChuraev" : "XWiki.dchuraev",
                "Denis B" : "XWiki.dbozhkov",
                "Denis Churaev" : "XWiki.dchuraev",
                "Dmitriy Mironov" : "XWiki.dmironov",
                "Dmitry Rozhdestvenskiy" : "XWiki.drozhdestvenskiy",
                "Dmitry Zelyanin" : "XWiki.dzelyanin",
                "Drozhdestvenskiy" : "XWiki.drozhdestvenskiy",
                "Dzelyanin" : "XWiki.dzelyanin",
                "E.Telkova" : "XWiki.esoboleva",
                "Ecowgill" : None,
                "Elena Vishina" : 'XWiki.evishina',
                "Eromanyuk" : "XWiki.eromanyuk",
                "Eugene Anufriev" : "XWiki.eanufriev",
                "Eugene Y." : 'XWiki.eyakovlev1',
                "Eugenia Mosunova" : 'XWiki.emosunova',
                "Evgenii Ivanov" : "XWiki.eivanov",
                "Fbelov" : "XWiki.fedorbelov",
                "FBozhanov" : "XWiki.fbozhanov",
                "Fedor Nikitin" : 'XWiki.fnikitin',
                "Glebgo" : "XWiki.ggorbachev",
                "guest" : "XWiki.guest",
                "Ikassihin" : "XWiki.ikassihin",
                "Ilya" : 'XWiki.isikorsky',
                "Ivan Goncharov" : None,
                "Ivan Kochemasov" : "XWiki.IKochemasov",
                "Izaitseva" : None,
                "Kate" : 'XWiki.kegorova',
                "Katerina" : 'XWiki.kegorova',
                "Kira Podlesnaja" : "XWiki.kpodlesnaja",
                "Kirill Avramenko" : 'XWiki.kavramenko',
                "Kirill Kuklin" : "XWiki.kkuklin",
                "Kirill Stetsko" : 'XWiki.KStetsko',
                "KirillK" : "XWiki.kkuklin",
                "Kkol" : "XWiki.Kkolobov",
                "Kliger" : None,
                "KPrimakov" : "XWiki.kprimakov",
                "Kreus" : None,
                "Ksenia Krasilschikova" : "XWiki.kkrasilschikova",
                "Maksim Ksenofontov" : "XWiki.MKsenofontov",
                "Maria_Z" : "XWiki.mzubareva",
                "MariaZ" : "XWiki.mzubareva",
                "Max Ksenofontov" : "XWiki.MKsenofontov",
                "Mburavtsov" : "XWiki.mburavtsov",
                "Mcheremisin" : "XWiki.mcheremisin",
                "MediaWiki default" : "XWiki.bot",
                "Michelle.randolph" : None,
                "Mihai Alexandru" : None,
                "Milligan" : None,
                "Mmatveev" : "XWiki.mmatveev",
                "Mshmakov" : None,
                "Mzolkin" : 'XWiki.mzolkin',
                "Nicos" : None,
                "Oleg Kulagin" : None,
                "Paul W." : None,
                "Phil.a" : None,
                "Pmukhin" : "XWiki.pmukhin",
                "Psvistunov" : None,
                "R2d2" : "XWiki.avoronkin",
                "RaducuLaura" : "XWiki.lraducu",
                "Rkovhaev" : "XWiki.rkovhaev",
                "Rkuksov" : None,
                "Roman Grechenev" : "XWiki.rgrechenev",
                "Romba" : "XWiki.rkudryashov",
                "Root" : "XWiki.bot",
                "Ruslan Kuleshov" : 'XWiki.ruslankuleshov',
                "Sergey Budarin" : "XWiki.sergeybudarin",
                "Sergey Denichenko" : "XWiki.sdenichenko",
                "Sergey Kochetkov" : "XWiki.skochetkov",
                "Skoch" : 'XWiki.skochetkov',
                "Snaumov" : None,
                "Stephen.phillips" : None,
                "Svyatoslav Vorona" : "XWiki.svorona",
                "Tat" : "XWiki.tkoroleva",
                "Terry.nikopoulos" : None,
                "Timur Begimov" : "XWiki.tbegimov",
                "TOLA" : 'XWiki.acherenkov',
                "TonyG" : None,
                "Tpayton" : None,
                "Ttuklin" : None,
                "Vadim Mordberg" : 'XWiki.vmordberg',
                "Vasiliy Pavlovich" : "XWiki.vpavlovich",
                "Vasiliy Yur" : "XWiki.vyur",
                "Viktoriia Meluzova" : 'XWiki.V',
                "Vindika Dissanayake" : None,
                "Vitaliy Andrienko" : "XWiki.vandrienko",
                "Vkuznetsov" : "XWiki.vkuznetsov",
                "VKuznetsova" : 'XWiki.VKuznetsova',
                "Vladimir Uspenskii" : None,
                "Vsemakin" : "XWiki.vsemakin",
                "Vyur" : "XWiki.vyur",
                "Vzenkevich" : None,
                "Vzubarev" : "XWiki.vzubarev",
                "Yan Skoursky" : None,
                "YariScur" : None,
                "Yrri" : None,
                "Zach.meyer" : None,
                "Кулешов Александр" : "XWiki.akuleshov",
                'Иван Беляев' : 'XWiki.ibelyaev',
                'Ibely' : 'XWiki.ibelyaev',
                'Pmakarov' : None,
                'Kavramenko' : 'XWiki.kavramenko',
                'Vsevolod Zubarev' : 'XWiki.vzubarev'
                    }
'''
for user, status in Users.items():
    if status is None:
        print(user)
'''